var menu_data = [
    {
      "name":"折线图",
      "class":"zx",
      "title":[
        {
          "name":"折线图",
          "type":"01",
          "img":"./img/zhexian/zx.png"
        },
        {
          "name":"面积堆积图",
          "type":"27",
          "img":"./img/zhexian/zx-dj.png"
        },
        {
          "name":"面积图",
          "type":"20",
          "img":"./img/zhexian/zx-mj.png"
        }
      ]
    },
    {
      "name":"柱状图",
      "class":"zhuzhuang",
      "title":[
        {
          "name":"堆积图",
          "type":"05",
          "img":"./img/zzt/zz-djt.png"
        },
        {
          "name":"横向堆积图",
          "type":"26",
          "img":"./img/zzt/zz-hxdjt.png"
        },
        {
          "name":"横向排名图",
          "type":"28",
          "img":"./img/zzt/zz-hxpmt.png"
        },
        {
          "name":"横向柱状图",
          "type":"21",
          "img":"./img/zzt/zz-hxzzt.png"
        },
        {
          "name":"柱状图",
          "type":"02",
          "img":"./img/zzt/zzu.png"
        },
        {
          "name":"柱线图",
          "type":"19",
          "img":"./img/zzt/zz-zxt.png"
        },
        {
          "name":"多颜色单数据柱状图",
          "type":"34",
          "img":"./img/zzt/ds.png"
        },
        {
          "name":"横向多颜色单数据柱状图",
          "type":"35",
          "img":"./img/zzt/ds1.png"
        }
      ]
    },
    {
      "name":"饼图",
      "class":"bingtu",
      "title":[
        {
          "name":"饼图",
          "type":"04",
          "img":"./img/bt/bt.png"
        },
        {
          "name":"南丁格尔玫瑰图",
          "type":"12",
          "img":"./img/bt/bt-nngemgt.png"
        },
        {
          "name":"内外环",
          "type":"23",
          "img":"./img/bt/bt-nwh.png"
        },
        {
          "name":"三层套图",
          "type":"30",
          "img":"./img/bt/bt-sctt.png"
        }
      ]
    },
    {
      "name":"地图",
      "class":"ditu",
      "title":[
        {
          "name":"百度地图路线",
          "type":"routeMap",
          "img":"./img/dt/dt-bddtlx.png"
        },
        {
          "name":"百度地图热力",
          "type":"heatMap",
          "img":"./img/dt/dt-bddtrl.png"
        },
        {
          "name":"地图热力+散点",
          "type":"22",
          "img":"./img/dt/dt-dtrljsd.png"
        },
        {
          "name":"迁徙图",
          "type":"13",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"地图热力",
          "type":"10",
          "img":"./img/dt/dt-dtrl.png"
        },
        {
          "name":"地图散点",
          "type":"09",
          "img":"./img/dt/dt-dtsd.png"
        }
      ]
    },
    {
      "name":"表格",
      "class":"biaoge",
      "title":[
        {
          "name":"跑马灯",
          "type":"06",
          "img":"./img/bg/bg-pmd.png"
        },
        {
          "name":"排名表",
          "type":"07",
          "img":"./img/bg/bg-pmb.png"
        },
        {
          "name":"信息块",
          "type":"08",
          "img":"./img/bg/bg-xxk.png"
        },
        {
          "name":"分页表格",
          "type":"25",
          "img":"./img/bg/bg-fybg.png"
        }

      ]
    },
    {
      "name":"关系图",
      "class":"guanxitu",
      "title":[
        {
          "name":"力导向图",
          "type":"15",
          "img":"./img/gxt/gxt-ldxt.png"
        },
        {
          "name":"圆形关系图",
          "type":"14",
          "img":"./img/gxt/gxt-yxgxt.png"
        },
        {
          "name":"自定义关系图",
          "type":"16",
          "img":"./img/gxt/gxt-zdygxt.png"
        }
      ]
    },
    {
      "name":"散点图",
      "class":"sandiantu",
      "title":[
        {
          "name":"散点图",
          "type":"03",
          "img":"./img/sdt/sdt-sdt.png"
        }
      ]
    },
    {
      "name":"热力图",
      "class":"relitu",
      "title":[
        {
          "name":"热力图",
          "type":"11",
          "img":"./img/rlt/rlt-rlt.png"
        }
      ]
    },
    {
      "name":"桑基图",
      "class":"sangjitu",
      "title":[
        {
          "name":"桑基图",
          "type":"17",
          "img":"./img/sjt/sjt-sjt.png"
        }
      ]
    },
    {
      "name":"文本",
      "class":"wenben",
      "title":[
        {
          "name":"文本",
          "type":"18",
          "img":"./img/wb/wb-wb.png"
        }
      ]
    },
    {
      "name":"人物画像",
      "class":"renwuhuaxiang",
      "title":[
        {
          "name":"人物画像",
          "type":"29",
          "img":"./img/rwhx/rwhx-rwhx.png"
        }
      ]
    },
    {
      "name":"仪表盘",
      "class":"ybp",
      "title":[
        {
          "name":"仪表盘",
          "type":"24",
          "img":"./img/ybp/ybp-ybp.png"
        }
      ]
    },
    {
      "name":"K线图",
      "class":"kxiantu",
      "title":[
        {
          "name":"K线图",
          "type":"31",
          "img":"./img/Kxt/Kxt-kxt.png"
        }
      ]
    },
    {
      "name":"流数据图",
      "class":"liushujutu",
      "title":[
        {
          "name":"单线心电图",
          "type":"32",
          "img":"./img/Kxt/Kxt-kxt.png"
        },
        {
          "name":"波浪图",
          "type":"33",
          "img":"./img/Kxt/Kxt-kxt.png"
        },
        {
          "name":"多线心电图",
          "type":"36",
          "img":"./img/Kxt/Kxt-kxt.png"
        }
      ]
    }
]
//选择图类型
/*$("#chartButton").click(function(){
	$("#smallChart").modal("toggle");
	for(var i=0;i<menu_data.length;i++){
		$(".navul").append('<li><a href="#" target="_self">'+menu_data[i].name+'</a></li>');
		$(".navul li:first").addClass('navbg');
		$(".navul li").click(function() {
			$(".content").html('');
			var n=$(".navul li").index(this)
			var div4='<div class="ajq">',div3='';
      for(var j=0;j<menu_data[n].title.length;j++){
        var div2='<a href="#" data-id="'+menu_data[n].title[j].type+'"><p>'+menu_data[n].title[j].name+'</p><img src="'+menu_data[n].title[j].img+'"></a>'
        div3+=div2
      }
      var div1='<div class="'+menu_data[n].class+'" id="">';
      var p1='<p class="title">'+menu_data[n].name+'</p>';
      var content=div1+p1+div4+div3+'</div>'+'</div>'
      $(".content").append(content)
		});
	}
});
*/
