var menu_data = [
    {
      "name":"折线图",
      "class":"zx",
      "title":[
        {
          "name":"折线图",
          "type":"01",
          "img":"./img/zhexian/zx.png"
        },
        {
          "name":"面积堆积图",
          "type":"27",
          "img":"./img/zhexian/zx-dj.png"
        },
        {
          "name":"面积图",
          "type":"20",
          "img":"./img/zhexian/zx-mj.png"
        }
      ]
    },
    {
      "name":"柱状图",
      "class":"zhuzhuang",
      "title":[
        {
          "name":"堆积图",
          "type":"05",
          "img":"./img/zzt/zz-djt.png"
        },
        {
          "name":"横向堆积图",
          "type":"26",
          "img":"./img/zzt/zz-hxdjt.png"
        },
        {
          "name":"横向排名图",
          "type":"28",
          "img":"./img/zzt/zz-hxpmt.png"
        },
        {
          "name":"横向柱状图",
          "type":"21",
          "img":"./img/zzt/zz-hxzzt.png"
        },
        {
          "name":"柱状图",
          "type":"02",
          "img":"./img/zzt/zzu.png"
        },
        {
          "name":"柱线图",
          "type":"19",
          "img":"./img/zzt/zz-zxt.png"
        },
        {
          "name":"多色单柱状图",
          "type":"34",
          "img":"./img/zzt/ds.png"
        },
        {
          "name":"横向多色单柱状图",
          "type":"35",
          "img":"./img/zzt/ds1.png"
        },
        {
          "name":"渐变柱线图",
          "type":"47",
          "img":"./img/zzt/zz-zxt.png"
        },
        {
          "name":"柱状对比图",
          "type":"49",
          "img":"./img/zzt/zz-zxt.png"
        },
        {
          "name":"柱线图双Y轴",
          "type":"53",
          "img":"./img/zzt/zz-zxt.png"
        }
      ]
    },
    {
      "name":"饼图",
      "class":"bingtu",
      "title":[
        {
          "name":"饼图",
          "type":"04",
          "img":"./img/bt/bt.png"
        },
        {
          "name":"南丁格尔玫瑰图",
          "type":"12",
          "img":"./img/bt/bt-nngemgt.png"
        },
        {
          "name":"内外环",
          "type":"23",
          "img":"./img/bt/bt-nwh.png"
        },
        {
          "name":"三层套图",
          "type":"30",
          "img":"./img/bt/bt-sctt.png"
        },
        {
          "name":"内外环阴影",
          "type":"48",
          "img":"./img/bt/bt-nwh.png"
        },
        {
          "name":"外环",
          "type":"50",
          "img":"./img/bt/bt-nwh.png"
        }
      ]
    },
    {
      "name":"地图",
      "class":"ditu",
      "title":[
        {
          "name":"百度地图路线",
          "type":"routeMap",
          "img":"./img/dt/dt-bddtlx.png"
        },
        {
          "name":"百度地图热力",
          "type":"heatMap",
          "img":"./img/dt/dt-bddtrl.png"
        },
        {
          "name":"地图热力散点图",
          "type":"22",
          "img":"./img/dt/dt-dtrljsd.png"
        },
        {
          "name":"迁徙图",
          "type":"13",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"地图热力",
          "type":"10",
          "img":"./img/dt/dt-dtrl.png"
        },
        {
          "name":"地图散点",
          "type":"09",
          "img":"./img/dt/dt-dtsd.png"
        },
        // {
        //   "name":"3D地图柱状图",
        //   "type":"42",
        //   "img":"./img/dt/dt-3Ddtsd.png"
        // },
        {
          "name":"地图散点排名图",
          "type":"43",
          "img":"./img/dt/dt-dtsd.png"
        },
        {
          "name":"双路线迁徙图",
          "type":"45",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"地图热力迁徙图",
          "type":"46",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"地图涟漪散点图",
          "type":"327",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"地图散点路线图",
          "type":"326",
          "img":"./img/dt/dt-qxt.png"
        }

      ]
    },
    {
      "name":"表格",
      "class":"biaoge",
      "title":[
        {
          "name":"跑马灯",
          "type":"06",
          "img":"./img/bg/bg-pmd.png"
        },
        {
          "name":"排名表",
          "type":"07",
          "img":"./img/bg/bg-pmb.png"
        },
        {
          "name":"信息块",
          "type":"08",
          "img":"./img/bg/bg-xxk.png"
        },
        {
          "name":"分页表格",
          "type":"25",
          "img":"./img/bg/bg-fybg.png"
        },
        {
          "name":"信息块303",
          "type":"303",
          "img":"./img/bg/bg-xxk303.png"
        },
        {
          "name":"信息块304",
          "type":"304",
          "img":"./img/bg/bg-xxk304.png"
        },
        {
          "name":"信息块305",
          "type":"305",
          "img":"./img/bg/bg-xxk305.png"
        },
        {
          "name":"表格",
          "type":"44",
          "img":"./img/bg/bg-pmb.png"
        },
        {
          "name":"表格新",
          "type":"58",
          "img":"./img/bg/bg-pmb.png"
        },
        {
          "name":"空",
          "type":"59",
          "img":"./img/bg/bg-pmb.png"
        }

      ]
    },
    {
      "name":"关系图",
      "class":"guanxitu",
      "title":[
        {
          "name":"力导向图",
          "type":"15",
          "img":"./img/gxt/gxt-ldxt.png"
        },
        {
          "name":"圆形关系图",
          "type":"14",
          "img":"./img/gxt/gxt-yxgxt.png"
        },
        {
          "name":"自定义关系图",
          "type":"16",
          "img":"./img/gxt/gxt-zdygxt.png"
        }
      ]
    },
    {
      "name":"散点图",
      "class":"sandiantu",
      "title":[
        {
          "name":"散点图",
          "type":"03",
          "img":"./img/sdt/sdt-sdt.png"
        },
        {
          "name":"散点图文字坐标",
          "type":"52",
          "img":"./img/sdt/sdt-sdt.png"
        }
      ]
    },
    {
      "name":"热力图",
      "class":"relitu",
      "title":[
        {
          "name":"热力图",
          "type":"11",
          "img":"./img/rlt/rlt-rlt.png"
        }
      ]
    },
    {
      "name":"桑基图",
      "class":"sangjitu",
      "title":[
        {
          "name":"桑基图",
          "type":"17",
          "img":"./img/sjt/sjt-sjt.png"
        }
      ]
    },
    {
      "name":"文本",
      "class":"wenben",
      "title":[
        {
          "name":"图片框",
          "type":"18",
          "img":"./img/wb/pic.jpg"
        },
        {
          "name":"HTML文本框",
          "type":"302",
          "img":"./img/wb/wb-wb.png"
        },
        {
          "name":"小标题",
          "type":"306",
          "img":"./img/bg/bg-xxk306.png"
        },
        {
          "name":"大标题",
          "type":"307",
          "img":"./img/bg/bg-xxk307.png"
        },
        {
          "name":"热点标题",
          "type":"309",
          "img":"./img/wb/rd_309.png"
        },
        {
          "name":"热点",
          "type":"310",
          "img":"./img/wb/rd_310.png"
        },
        {
          "name":"有图热点",
          "type":"312",
          "img":"./img/wb/rd_312.png"
        },
        {
          "name":"无图热点",
          "type":"313",
          "img":"./img/wb/rd_313.png"
        },
        {
          "name":"本地时间",
          "type":"319",
          "img":"./img/wb/rd_313.png"
        },
        {
          "name":"面积排序",
          "type":"318",
          "img":"./img/wb/rd_313.png"
        },
        {
          "name":"工具条",
          "type":"54",
          "img":"./img/wb/rd_313.png"
        }
      ]
    },
    {
      "name":"人物画像",
      "class":"renwuhuaxiang",
      "title":[
        {
          "name":"人物画像",
          "type":"29",
          "img":"./img/rwhx/rwhx-rwhx.png"
        }
      ]
    },
    {
      "name":"仪表盘",
      "class":"ybp",
      "title":[
        {
          "name":"仪表盘",
          "type":"24",
          "img":"./img/ybp/ybp-ybp.png"
        },
        {
          "name":"3仪表盘",
          "type":"41",
          "img":"./img/ybp/ybp-ybp3.png"
        },
        {
          "name":"2仪表盘",
          "type":"51",
          "img":"./img/ybp/ybp-ybp3.png"
        }
      ]
    },
    {
      "name":"K线图",
      "class":"kxiantu",
      "title":[
        {
          "name":"K线图",
          "type":"31",
          "img":"./img/Kxt/Kxt-kxt.png"
        }
      ]
    },
    {
      "name":"流数据图",
      "class":"liushujutu",
      "title":[
        {
          "name":"单线心电图",
          "type":"32",
          "img":"./img/Kxt/xdt_one.jpg"
        },
        {
          "name":"单线波浪图",
          "type":"33",
          "img":"./img/Kxt/xdt_two.jpg"
        },
        {
          "name":"多线心电图",
          "type":"36",
          "img":"./img/Kxt/xdt_three.jpg"
        },
        {
          "name":"多线波浪图",
          "type":"38",
          "img":"./img/Kxt/dxbl.jpg"
        },
        {
          "name":"实时路线图",
          "type":"301",
          "img":"./img/Kxt/gjt.jpg"
        }
      ]
    },
    {
      "name":"雷达图",
      "class":"leidatu",
      "title":[
        {
          "name":"雷达图",
          "type":"39",
          "img":"./img/Kxt/radar-aqi.png"
        },
      ]
    },
    {
      "name":"3D图",
      "class":"3dzt",
      "title":[
        {
          "name":"3d柱图",
          "type":"314",
          "img":"./img/Kxt/radar-aqi.png"
        },
        {
          "name":"3d进度图",
          "type":"317",
          "img":"./img/Kxt/radar-aqi.png"
        },
        {
          "name":"3d地图柱子",
          "type":"315",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"3d旋转地图",
          "type":"316",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"3d攻击路线图1",
          "type":"320",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"3d攻击路线图2",
          "type":"321",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"3d轮廓地球",
          "type":"322",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"3d实时攻击路线图1",
          "type":"323",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"3d实时攻击路线图2",
          "type":"324",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"3d轮廓实时攻击路线图",
          "type":"325",
          "img":"./img/dt/dt-qxt.png"
        },
        {
          "name":"3D地球板状",
          "type":"326",
          "img":"./img/dt/dt-qxt.png"
        }
      ]
    },
    {
      "name":"动画插件",
      "class":"dhcj",
      "title":[
        {
          "name":"动画插件1",
          "type":"55",
          "img":"./img/Kxt/radar-aqi.png"
        },
        {
          "name":"动画插件2",
          "type":"56",
          "img":"./img/Kxt/radar-aqi.png"
        },
        {
          "name":"动画插件3",
          "type":"57",
          "img":"./img/dt/dt-qxt.png"
        }
      ]
    }
]
